unique_ids:
  assets:
    standard-page.html: XMSBNRGTNLGU23DWOKXP7J6KBHI6IXBX
    theme.css: 5JYQCY7YZCKLKZXGHIBL5S42URDHERA7
  forms:
    Form1: L6ARUKCMRQCKSA7TX4FPBHVBNYAMSG5J
  modules: {}
  scripts: {}
  server_modules: {}
